#
# /etc/pacman.conf - AArchDroid with BlackArch repos
#

[options]
HoldPkg      = pacman glibc
Architecture = aarch64
Color
#CheckSpace (disabled — f2fs returns f_fsid=0, pacman can't detect mount point)
VerbosePkgLists
ParallelDownloads = 5
DisableSandbox
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[alarm]
Include = /etc/pacman.d/mirrorlist

[aur]

# BlackArch - Complete Pentesting Suite
[blackarch]
SigLevel = Never
Server = https://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch
Server = https://mirrors.sjtug.sjtu.edu.cn/blackarch/$repo/os/$arch
Server = https://mirror.aktkn.sg/blackarch/$repo/os/$arch
